version: "3"

services:
  frontend:
    build: 
        dockerfile: ../.devcontainer/frontend.Dockerfile
        context: client
    container_name: client
    restart: always
    ports:
      - 5173:5173
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    build: 
        dockerfile: ./.devcontainer/backend.Dockerfile 
        context: .
    container_name: server
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo: